### PR TITLE
Remove flask app secret key

### PR DESCRIPTION
**Pull request by KomalBhadani27**
Removed secret key because we are not using sessions anymore

### CODE REVIEW

**Comment by detel** [comment]
Update the [docker README](https://github.com/googleinterns/stampify/blob/master/README.md#build) as well.
Search for `FLASK_APP_SECRET_KEY` in entire project.

**Comment by KomalBhadani27** [comment]
> Update the [docker README](https://github.com/googleinterns/stampify/blob/master/README.md#build) as well.
> Search for `FLASK_APP_SECRET_KEY` in entire project.

Updated in [#148](https://github.com/googleinterns/stampify/pull/148)

**Comment by detel** [comment]
> > Update the [docker README](https://github.com/googleinterns/stampify/blob/master/README.md#build) as well.
> > Search for `FLASK_APP_SECRET_KEY` in entire project.
> 
> Updated in [#148](https://github.com/googleinterns/stampify/pull/148)

It is recommended to have same changes in one PR.

**Review by detel — APPROVED** [review]

**Comment by KomalBhadani27** [comment]
> > > Update the [docker README](https://github.com/googleinterns/stampify/blob/master/README.md#build) as well.
> > > Search for `FLASK_APP_SECRET_KEY` in entire project.
> > 
> > 
> > Updated in [#148](https://github.com/googleinterns/stampify/pull/148)
> 
> It is recommended to have same changes in one PR.

Actually I did README change in that PR because it was related to readme update. I removed it from everywhere in code in this PR only. Though will take care from next time. Thanks for suggestion!

**Pull request merged**
